In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("한국산업단지공단_전국등록공장현황_등록공장현황자료_20241231.csv", encoding = 'cp949')
df

,순번,회사명,단지명,생산품,공장주소
0,1,남일문화 (주),,인쇄물,서울특별시 종로구 자하문로16길 8 (창성동)
1,2,(주)에취.알.디,,"모형전시물,IC TESTER외",서울특별시 종로구 통의동 35-69번지
2,3,(주)코리아쉬핑가제트,,주간신문,서울특별시 종로구 자하문로2길 13-3 (통의동)
3,4,삼영DP,,인쇄,서울특별시 종로구 사직로 125 (적선동)
4,5,중앙인쇄사,,인쇄물,서울특별시 종로구 자하문로2길 18 (적선동)
...,...,...,...,...,...
217043,217044,제이페이퍼 주식회사,부안줄포농공단지,"제트테이프,숯초배지",전북특별자치도 부안군 줄포면 농공단지길 6
217044,217045,유한회사 줄포하늘수산,,생선가공품,전북특별자치도 부안군 줄포면 신리로 313-12
217045,217046,남부안농업협동조합,,유기질비료,전북특별자치도 부안군 줄포면 장산로 139-9 (농협DSC공장) (총 2 필지) 외...
217046,217047,지산정미소,,쌀,전북특별자치도 부안군 줄포면 율지길 33
217047,217048,금영수산,,건멸치,전북특별자치도 부안군 위도면 식도리 1-24번지

In [10]:
df1 = df[df['생산품'].str.contains("반도체")] # 생산품 열에서 반도체 문자열을 포함하고 있는 행을 추출
df1

,순번,회사명,단지명,생산품,공장주소
1436,1437,(주)리우솔루션,,"반도체부품,자동자어반,cctv","서울특별시 성동구 성수일로 89, 304호 (성수동1가)"
1514,1515,세진테크,,반도체부품,"서울특별시 성동구 뚝섬로1길 31, 지하2층 208호 (성수동1가)"
1709,1710,(주)소닉스,,"화상인식장치,반도체제어장비","서울특별시 성동구 성수이로24길 38, 7층 703호 (성수동2가, 신흥아파트형공장)"
3242,3243,(주)마이크로프랜드,,반도체 검사장치,"서울특별시 노원구 공릉로 232, 서울테크노파크 FAB 2층 (공릉동)"
3752,3753,(주)베리룩스테크놀로지,,반도체검사장비,"서울특별시 강서구 공항대로61길 29, 서울신기술창업센터 A-101 (등촌동)"
...,...,...,...,...,...
215536,215537,(유)씨피전자,전주과학산업연구단지,"다이오드, 트랜지스터, 유사반도체",전북특별자치도 완주군 봉동읍 둔산1로 36 (CP전자)
215537,215538,(유)에스엔지반도체,전주과학산업연구단지,반도체실리콘웨이퍼,전북특별자치도 완주군 봉동읍 완주산단6로 224 (전북과학연구소)
215589,215590,(주)알에프세미,전주과학산업연구단지,마이크용 반도체 칩,전북특별자치도 완주군 봉동읍 완주산단6로 12 (알에프세미) (총 3 필지) 외 1필지
215645,215646,미원상사(주) 전주2공장,전주과학산업연구단지,"화장품등의 원료, 반도체, LCD원료, 도료, 잉크원료",전북특별자치도 완주군 봉동읍 완주산단6로 56 (미원상사)
215940,215941,(주)플래닝썬,,반도체 소자,"전북특별자치도 완주군 이서면 콩쥐팥쥐로 1043-7 ,2동 104호 전북대 창업보육3센타"

In [70]:
df1['지역'] = df1['공장주소'].str.extract(r'(\S+[시군구])') # 공장주소에서 시군구 추출
df1

,순번,회사명,단지명,생산품,공장주소,지역
1436,1437,(주)리우솔루션,,"반도체부품,자동자어반,cctv","서울특별시 성동구 성수일로 89, 304호 (성수동1가)",서울특별시
1514,1515,세진테크,,반도체부품,"서울특별시 성동구 뚝섬로1길 31, 지하2층 208호 (성수동1가)",서울특별시
1709,1710,(주)소닉스,,"화상인식장치,반도체제어장비","서울특별시 성동구 성수이로24길 38, 7층 703호 (성수동2가, 신흥아파트형공장)",서울특별시
3242,3243,(주)마이크로프랜드,,반도체 검사장치,"서울특별시 노원구 공릉로 232, 서울테크노파크 FAB 2층 (공릉동)",서울특별시
3752,3753,(주)베리룩스테크놀로지,,반도체검사장비,"서울특별시 강서구 공항대로61길 29, 서울신기술창업센터 A-101 (등촌동)",서울특별시
...,...,...,...,...,...,...
215536,215537,(유)씨피전자,전주과학산업연구단지,"다이오드, 트랜지스터, 유사반도체",전북특별자치도 완주군 봉동읍 둔산1로 36 (CP전자),완주군
215537,215538,(유)에스엔지반도체,전주과학산업연구단지,반도체실리콘웨이퍼,전북특별자치도 완주군 봉동읍 완주산단6로 224 (전북과학연구소),완주군
215589,215590,(주)알에프세미,전주과학산업연구단지,마이크용 반도체 칩,전북특별자치도 완주군 봉동읍 완주산단6로 12 (알에프세미) (총 3 필지) 외 1필지,완주군
215645,215646,미원상사(주) 전주2공장,전주과학산업연구단지,"화장품등의 원료, 반도체, LCD원료, 도료, 잉크원료",전북특별자치도 완주군 봉동읍 완주산단6로 56 (미원상사),완주군
215940,215941,(주)플래닝썬,,반도체 소자,"전북특별자치도 완주군 이서면 콩쥐팥쥐로 1043-7 ,2동 104호 전북대 창업보육3센타",완주군

In [69]:
df1[df1['지역'].isna()] # 공장주소가 비어있는 데이터들

,순번,회사명,단지명,생산품,공장주소,지역
32258,32259,(주)연우테크,인천일반산업단지,반도체 조립용 장비,,NaN
58460,58461,(주)레이크머티리얼즈,세종미래일반산업단지,반도체 소재(TEOS),,NaN
60187,60188,㈜우노실리콘,판교제2테크노밸리,반도체 설계,,NaN
69623,69624,(주)글로벌스탠다드테크놀로지,,반도체장비 제조,,NaN
70600,70601,엘오에스,,금속가공품(반도체장비),,NaN
...,...,...,...,...,...,...
174419,174420,(주)원익큐엔씨 산동사업장,구미국가산업단지,반도체용석영유리가공,,NaN
174420,174421,(주)월덱스 캠퍼스2,구미국가산업단지,반도체장비부품,,NaN
185167,185168,거성정밀,상복일반산업단지,"우주선엔진, 항공기 엔진부품, 방산부품, 반도체장비부품",,NaN
207516,207517,주식회사 엔에스테크닉스,태백동점산업단지,반도체 공정용 탄소부품,,NaN
213069,213070,타코마테크놀러지(주),익산제3일반산업단지,"카도바인더수지, 반도체용 소재 등",,NaN

In [80]:
df2 = df1.groupby('지역') # 지역별로 묶음
df2.size().sort_values(ascending = False).head(50) # 내림차순으로 50개의 데이터만 출력

지역
화성시        614
천안시        311
인천광역시      287
안산시        251
시흥시        210
아산시        202
평택시        199
안성시        137
청주시        137
구미시        121
용인시        102
수원시         90
대전광역시       75
대구광역시       72
부천시         70
창원시         68
서울특별시       63
성남시         56
군포시         50
부산광역시       43
천안시서북구      36
이천시         33
오산시         33
김포시         32
파주시         31
음성군         30
진천군         21
안양시         19
익산시         15
김해시         14
광주시         14
양산시         12
의왕시         12
광주광역시       12
칠곡군         12
광명시         11
당진시         11
세종특별자치시      8
남양주시         7
전주시          7
함안군          7
완주군          7
울산광역시        7
하남시          6
공주시          6
강릉시          4
예산군          4
보은군          4
성주군          4
경산시          4
dtype: int64